# Generated by Django 5.1.5 on 2026-01-30 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignrecipient',
            name='client_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_recipients', to='contacts.clientcontact'),
        ),
        migrations.AddField(
            model_name='campaignrecipient',
            name='delegate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_recipients', to='contacts.delegate'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsletters', to='campaigns.campaign'),
        ),
    ]
