# Generated by Django 5.1.5 on 2026-01-30 14:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('contacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('interviewing', 'Interviewing'), ('offered', 'Offered'), ('filled', 'Filled'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('job_type', models.CharField(choices=[('permanent', 'Permanent'), ('contract', 'Contract'), ('temp', 'Temporary'), ('temp_to_perm', 'Temp to Perm')], default='permanent', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('requirements', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fee_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='clients.client')),
                ('consultant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('stage', models.CharField(choices=[('sourced', 'Sourced'), ('applied', 'Applied'), ('screening', 'Screening'), ('shortlisted', 'Shortlisted'), ('submitted', 'Submitted to Client'), ('interviews', 'Interviews'), ('offer', 'Offer'), ('placed', 'Placed'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='sourced', max_length=20)),
                ('cv', models.FileField(blank=True, upload_to='cvs/candidates/')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('salary_expectation', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('delegate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidacies', to='contacts.delegate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='recruitment.job')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending_start', 'Pending Start'), ('started', 'Started'), ('probation', 'Probation'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending_start', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('agreed_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('guarantee_period_days', models.PositiveIntegerField(default=90)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='placement', to='recruitment.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='recruitment.job')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
