# Generated by Django 5.1.5 on 2026-01-30 14:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('objectives', models.TextField(blank=True)),
                ('duration_days', models.DecimalField(decimal_places=1, default=1, max_digits=4)),
                ('max_delegates', models.PositiveIntegerField(default=12)),
                ('min_delegates', models.PositiveIntegerField(default=1)),
                ('delivery_method', models.CharField(choices=[('classroom', 'Classroom'), ('virtual', 'Virtual'), ('blended', 'Blended'), ('elearning', 'E-Learning')], default='classroom', max_length=20)),
                ('price_per_delegate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_bespoke', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('accreditation_body', models.CharField(blank=True, max_length=255)),
                ('accreditation_number', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='CourseInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=255)),
                ('virtual_link', models.URLField(blank=True)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('client', models.ForeignKey(blank=True, help_text='Set if this is a bespoke course for a specific client', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bespoke_instances', to='clients.client')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='training.course')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_instances', to='contacts.trainer')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('provisional', 'Provisional'), ('confirmed', 'Confirmed'), ('attended', 'Attended'), ('no_show', 'No Show'), ('cancelled', 'Cancelled')], default='provisional', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('po_number', models.CharField(blank=True, max_length=100)),
                ('certificate_issued', models.BooleanField(default=False)),
                ('certificate_number', models.CharField(blank=True, max_length=100)),
                ('feedback_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('feedback_comments', models.TextField(blank=True)),
                ('booked_by_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='clients.client')),
                ('booked_by_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings_made', to='contacts.clientcontact')),
                ('delegate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='contacts.delegate')),
                ('course_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='training.courseinstance')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
