# Generated by Django 5.1.5 on 2026-01-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_remove_booking_feedback_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='delivery_method',
            field=models.CharField(choices=[('face_to_face', 'Face to Face'), ('video', 'Video'), ('vr', 'VR'), ('elearning', 'E-Learning'), ('webinar', 'Webinar'), ('blended', 'Blended')], default='face_to_face', max_length=20),
        ),
    ]
