# Generated by Django 5.1.5 on 2026-01-30 16:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_homepage', models.BooleanField(default=False, help_text='If true, this page is used as the landing page.')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('section_type', models.CharField(choices=[('hero', 'Hero Banner'), ('text', 'Text Block'), ('image', 'Image'), ('image_text', 'Image + Text'), ('video', 'Video Embed'), ('gallery', 'Gallery'), ('cta', 'Call to Action'), ('cards', 'Card Grid'), ('testimonials', 'Testimonials'), ('faq', 'FAQ'), ('form', 'Form Embed'), ('html', 'Custom HTML'), ('spacer', 'Spacer')], default='text', max_length=20)),
                ('content', models.JSONField(blank=True, default=dict, help_text='Structured content for this section (varies by section_type).')),
                ('is_visible', models.BooleanField(default=True)),
                ('css_class', models.CharField(blank=True, help_text='Optional CSS classes for custom styling.', max_length=255)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='pages.page')),
            ],
            options={
                'ordering': ['page', 'order'],
                'unique_together': {('page', 'order')},
            },
        ),
    ]
