# Generated by Django 5.1.5 on 2026-01-30 14:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('trading_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('prospect', 'Prospect'), ('active', 'Active'), ('inactive', 'Inactive'), ('former', 'Former')], default='prospect', max_length=20)),
                ('client_type', models.CharField(choices=[('training', 'Training'), ('recruitment', 'Recruitment'), ('both', 'Both')], default='training', max_length=20)),
                ('company_number', models.CharField(blank=True, max_length=30)),
                ('vat_number', models.CharField(blank=True, max_length=30)),
                ('website', models.URLField(blank=True)),
                ('industry', models.CharField(blank=True, max_length=150)),
                ('address_line_1', models.CharField(blank=True, max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('postcode', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(default='United Kingdom', max_length=100)),
                ('billing_email', models.EmailField(blank=True, max_length=254)),
                ('payment_terms_days', models.PositiveIntegerField(default=30)),
                ('lifetime_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('portal_enabled', models.BooleanField(default=False)),
                ('account_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
